# Site settings
title: Stockton on the Forest Primary School Code Club
email: edward@aldreth.com
description: > # this means to ignore newlines until "baseurl:"
  Pages built by children at Stockton on the Forest Primary School Code Club
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.stocktoncodeclub.org.uk/" # the base hostname & protocol for your site
twitter_username:
github_username:  aldreth

# Build settings
markdown: kramdown
